"""
Django settings for AYH project.
Generated by 'django-admin startproject' using Django 5.2.10.
"""

from pathlib import Path
import os
from datetime import timedelta

BASE_DIR = Path(__file__).resolve().parent.parent

def _load_dotenv_if_present():
    """
    Lightweight .env loader for local development.
    We only set keys that are not already in os.environ.
    """
    env_path = BASE_DIR / ".env"
    if not env_path.exists():
        return
    try:
        raw = env_path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        raw = env_path.read_text(encoding="utf-8-sig")
    for line in raw.splitlines():
        s = line.strip()
        if not s or s.startswith("#"):
            continue
        if s.lower().startswith("export "):
            s = s[7:].lstrip()
        if "=" not in s:
            continue
        key, value = s.split("=", 1)
        key = key.strip()
        value = value.strip().strip("'").strip('"')
        if key and key not in os.environ:
            os.environ[key] = value


_load_dotenv_if_present()

def _make_config():
    try:
        from decouple import Config, RepositoryEnv
        _env_path = BASE_DIR / ".env"
        if _env_path.exists():
            return Config(repository=RepositoryEnv(str(_env_path)))
        from decouple import config as _c
        return _c
    except ImportError:
        def config(key, default=None, cast=None):
            val = os.environ.get(key, default)
            if val is None:
                return None
            if cast is bool:
                return str(val).lower() in ("1", "true", "yes", "on")
            return val
        return config

config = _make_config()

# ==============================================================================
# SECURITY
# ==============================================================================

SECRET_KEY = config(
    "DJANGO_SECRET_KEY",
    default="django-insecure-38eb&2sar0s=x(93uf$yxu7ab4s!*7$ayf0^z^*70y!8g7)h$b",
)

# Consider Vercel as production by default
IS_PRODUCTION = (config("DJANGO_ENV", default="") == "production") or bool(os.environ.get("VERCEL"))

# Default to DEBUG=False in production unless explicitly enabled
DEBUG = config("DJANGO_DEBUG", default=not IS_PRODUCTION, cast=bool)

ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    ".vercel.app",
]
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# ==============================================================================
# APPLICATIONS
# ==============================================================================

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Third-party apps
    "rest_framework",
    "rest_framework_simplejwt",
    "corsheaders",

    # Local apps
    "careapp",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",

    "corsheaders.middleware.CorsMiddleware",  # must be before CommonMiddleware
    "django.contrib.sessions.middleware.SessionMiddleware",

    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "AYH.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.template.context_processors.csrf",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "careapp.context_processors.admin_notifications",
                "careapp.context_processors.donor_notification_count",
            ],
        },
    },
]

WSGI_APPLICATION = "AYH.wsgi.application"

# ==============================================================================
# DATABASE (Supabase / Vercel safe)
# ==============================================================================

import dj_database_url

DATABASE_URL = os.environ.get("DATABASE_URL")

if DATABASE_URL:
    DATABASES = {
        "default": dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
    DATABASES["default"].setdefault("OPTIONS", {})
    DATABASES["default"]["OPTIONS"]["sslmode"] = "require"
else:
    # Local fallback only
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": str(BASE_DIR / "db.sqlite3"),
        }
    }

# Force DATABASE_URL on Vercel (prevents accidental sqlite in prod)
if os.environ.get("VERCEL") and not DATABASE_URL:
    raise RuntimeError("DATABASE_URL is missing on Vercel. Add it in Vercel env vars.")

# ==============================================================================
# PASSWORD VALIDATORS
# ==============================================================================

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# ==============================================================================
# INTERNATIONALIZATION
# ==============================================================================

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# ==============================================================================
# STATIC / MEDIA
# ==============================================================================

STATIC_URL = "/static/"

STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_DIRS = [
    BASE_DIR / "careapp" / "static",
]


if os.environ.get("VERCEL"):
    # On Vercel, avoid manifest lookups if collectstatic isn't persisted.
    STATICFILES_STORAGE = "whitenoise.storage.CompressedStaticFilesStorage"
else:
    STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Allow WhiteNoise to serve directly from app static dirs when needed
WHITENOISE_USE_FINDERS = True

MEDIA_URL = "/media/"
MEDIA_ROOT = str(BASE_DIR / "media")

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ==============================================================================
# AUTH / LOGIN ROUTES (keep ONE set)
# ==============================================================================

LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "/home/"
LOGOUT_REDIRECT_URL = "/accounts/login/"

# ==============================================================================
# SESSIONS (Lifetime login)
# ==============================================================================

SESSION_ENGINE = "django.contrib.sessions.backends.db"
SESSION_COOKIE_AGE = 60 * 60 * 24 * 365  # 1 year
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# Cookies: secure only on HTTPS/production
SESSION_COOKIE_SECURE = IS_PRODUCTION
CSRF_COOKIE_SECURE = IS_PRODUCTION

# If production and your frontend is on another domain, you need SameSite=None + Secure
SESSION_COOKIE_SAMESITE = "None" if IS_PRODUCTION else "Lax"
CSRF_COOKIE_SAMESITE = "None" if IS_PRODUCTION else "Lax"

CSRF_COOKIE_HTTPONLY = False
CSRF_USE_SESSIONS = False
CSRF_COOKIE_AGE = 31449600
CSRF_COOKIE_DOMAIN = None
CSRF_COOKIE_PATH = "/"

# Build CSRF trusted origins: localhost + Vercel wildcard + explicit production URL
_CSRF_ORIGINS = [
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "https://*.vercel.app",
]
# Add exact production URL so cookies/redirects and admin login work on Vercel
_APP_BASE = config("APP_BASE_URL", default="").strip().rstrip("/")
if _APP_BASE and (_APP_BASE.startswith("https://") or _APP_BASE.startswith("http://")):
    _CSRF_ORIGINS.append(_APP_BASE)
# When on Vercel, also trust VERCEL_URL so we don't rely on APP_BASE_URL being set
if os.environ.get("VERCEL"):
    _vurl = os.environ.get("VERCEL_URL", "").strip()
    if _vurl:
        _CSRF_ORIGINS.append(f"https://{_vurl.rstrip('/')}")
CSRF_TRUSTED_ORIGINS = _CSRF_ORIGINS
CSRF_FAILURE_VIEW = "django.views.csrf.csrf_failure"

# ==============================================================================
# REST FRAMEWORK
# ==============================================================================

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ],
    "DEFAULT_FILTER_BACKENDS": [
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "100/hour",
        "user": "1000/hour",
    },
    "DATETIME_FORMAT": "%Y-%m-%d %H:%M:%S",
    "DATE_FORMAT": "%Y-%m-%d",
}

# ==============================================================================
# JWT
# ==============================================================================

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
}

# ==============================================================================
# CORS
# ==============================================================================

if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
else:
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:3000",
        "http://127.0.0.1:3000",
        # "https://yourdomain.com",
    ]

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = ["DELETE", "GET", "OPTIONS", "PATCH", "POST", "PUT"]

CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

# ==============================================================================
# CACHE (for OTP and similar)
# ==============================================================================

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
    }
}

# OTP SMS (registration) – set in .env to send real OTP to mobile
# Options: "console" (log only), "twilio", "twilio_verify" (use Service SID, no from number), "msg91", "fast2sms"
OTP_SMS_BACKEND = config("OTP_SMS_BACKEND", default="console")
# Fast2SMS (India): get API key from https://www.fast2sms.com/
FAST2SMS_API_KEY = config("FAST2SMS_API_KEY", default=None)
# Twilio (global): for "twilio" use FROM_NUMBER; for "twilio_verify" use VERIFY_SERVICE_SID only
TWILIO_ACCOUNT_SID = config("TWILIO_ACCOUNT_SID", default=None)
TWILIO_AUTH_TOKEN = config("TWILIO_AUTH_TOKEN", default=None)
TWILIO_FROM_NUMBER = config("TWILIO_FROM_NUMBER", default=None)
TWILIO_VERIFY_SERVICE_SID = config("TWILIO_VERIFY_SERVICE_SID", default=None)
# MSG91 (India): MSG91_AUTH_KEY, optional MSG91_OTP_TEMPLATE_ID
MSG91_AUTH_KEY = config("MSG91_AUTH_KEY", default=None)
MSG91_OTP_TEMPLATE_ID = config("MSG91_OTP_TEMPLATE_ID", default=None)

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# On Vercel, default to deployment URL so OAuth redirect/callback and CSRF work
_default_base = "http://localhost:8000"
if os.environ.get("VERCEL"):
    _vercel_url = os.environ.get("VERCEL_URL", "").strip()
    if _vercel_url:
        _default_base = f"https://{_vercel_url.rstrip('/')}"


SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

APP_BASE_URL = config("APP_BASE_URL", default="http://localhost:8000").rstrip("/")

GOOGLE_OAUTH_CLIENT_ID = config("GOOGLE_OAUTH_CLIENT_ID", default=None)
GOOGLE_OAUTH_CLIENT_SECRET = config("GOOGLE_OAUTH_CLIENT_SECRET", default=None)

GOOGLE_REDIRECT_URI = config(
    "GOOGLE_REDIRECT_URI",
    default=f"{APP_BASE_URL}/register/google/callback/",
)
# ==============================================================================
# BLOOD REQUEST LOCATION
# ==============================================================================

DEFAULT_RADIUS_KM = 10
