# Generated by Django 5.1 on 2026-02-10 18:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodBankMaster',
            fields=[
                ('blood_bank_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('reliability_score', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DimDate',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('quarter', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DonorOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('otp_code', models.CharField(max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HospitalMaster',
            fields=[
                ('hospital_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('hospital_name', models.CharField(max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('tier', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'ordering': ['hospital_name'],
            },
        ),
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('hospital_id', models.CharField(blank=True, db_index=True, max_length=50)),
                ('patient_age', models.PositiveIntegerField(blank=True, null=True)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3)),
                ('units_needed', models.PositiveIntegerField(default=1)),
                ('units_required', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('urgency', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium')], max_length=10)),
                ('urgency_level', models.CharField(blank=True, max_length=20)),
                ('source', models.CharField(blank=True, choices=[('app', 'App'), ('call', 'Call'), ('hospital', 'Hospital')], default='app', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('fulfilled', 'Fulfilled'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='open', max_length=20)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closure_reason', models.CharField(blank=True, choices=[('success', 'Success'), ('timeout', 'Timeout'), ('cancelled', 'Cancelled')], max_length=20)),
                ('closure_type', models.CharField(blank=True, choices=[('donor', 'Donor'), ('bloodbank', 'BloodBank'), ('mixed', 'Mixed')], max_length=20)),
                ('sla_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('req_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('req_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_name', models.CharField(blank=True, max_length=255)),
                ('radius_km', models.FloatField(default=5.0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BloodBankFallback',
            fields=[
                ('bank_fallback_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('units_requested', models.PositiveIntegerField(default=1)),
                ('units_confirmed', models.PositiveIntegerField(blank=True, null=True)),
                ('contacted_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('eta_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('blood_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fallbacks', to='careapp.bloodbankmaster')),
                ('request', models.ForeignKey(db_column='request_id', on_delete=django.db.models.deletion.CASCADE, related_name='blood_bank_fallbacks', to='careapp.bloodrequest')),
            ],
            options={
                'ordering': ['-contacted_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('request_created', 'Request Created'), ('donor_accepted', 'Donor Accepted')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_notifications_as_donor', to=settings.AUTH_USER_MODEL)),
                ('blood_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_notifications', to='careapp.bloodrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DelayReason',
            fields=[
                ('delay_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.CharField(choices=[('Search', 'Search'), ('Acceptance', 'Acceptance'), ('Transit', 'Transit')], max_length=30)),
                ('delay_reason', models.CharField(max_length=100)),
                ('delay_category', models.CharField(blank=True, choices=[('Supply', 'Supply'), ('Distance', 'Distance'), ('Ops', 'Ops')], max_length=30)),
                ('delay_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('identified_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved', models.BooleanField(default=False)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_delay_reasons', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(db_column='request_id', on_delete=django.db.models.deletion.CASCADE, related_name='delay_reasons', to='careapp.bloodrequest')),
            ],
            options={
                'ordering': ['-identified_at'],
            },
        ),
        migrations.CreateModel(
            name='DimCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['city', 'state'],
                'unique_together': {('city', 'state')},
            },
        ),
        migrations.CreateModel(
            name='DonorAssignment',
            fields=[
                ('assignment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('donor_type', models.CharField(choices=[('Primary', 'Primary'), ('Standby', 'Standby')], default='Primary', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('dropped_at', models.DateTimeField(blank=True, null=True)),
                ('drop_reason', models.CharField(blank=True, max_length=100)),
                ('eta_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Dropped', 'Dropped'), ('Completed', 'Completed')], default='Accepted', max_length=20)),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donor_assignments', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(db_column='request_id', on_delete=django.db.models.deletion.CASCADE, related_name='donor_assignments', to='careapp.bloodrequest')),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='DonorMovement',
            fields=[
                ('movement_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location_lat', models.FloatField(blank=True, null=True)),
                ('location_long', models.FloatField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('distance_remaining_km', models.FloatField(blank=True, null=True)),
                ('eta_remaining_min', models.PositiveIntegerField(blank=True, null=True)),
                ('assignment', models.ForeignKey(db_column='assignment_id', on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='careapp.donorassignment')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='DonorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('phone_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('last_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_updated_at', models.DateTimeField(blank=True, null=True)),
                ('donor_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('last_donation_date', models.DateField(blank=True, null=True)),
                ('availability_status', models.CharField(choices=[('Available', 'Available'), ('Busy', 'Busy')], default='Available', max_length=20)),
                ('reliability_score', models.FloatField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='donor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='donorassignment',
            name='donor_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='careapp.donorprofile'),
        ),
        migrations.CreateModel(
            name='EtaTracking',
            fields=[
                ('eta_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('Donor', 'Donor'), ('BloodBank', 'BloodBank')], max_length=20)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('committed_eta_min', models.PositiveIntegerField(blank=True, null=True)),
                ('actual_arrival_at', models.DateTimeField(blank=True, null=True)),
                ('actual_duration_min', models.PositiveIntegerField(blank=True, null=True)),
                ('eta_breached', models.BooleanField(default=False)),
                ('breach_minutes', models.IntegerField(blank=True, null=True)),
                ('request', models.ForeignKey(db_column='request_id', on_delete=django.db.models.deletion.CASCADE, related_name='eta_trackings', to='careapp.bloodrequest')),
            ],
            options={
                'ordering': ['-committed_at'],
            },
        ),
        migrations.CreateModel(
            name='FallbackAction',
            fields=[
                ('fallback_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fallback_type', models.CharField(choices=[('Radius', 'Radius'), ('Standby', 'Standby'), ('Bank', 'Bank'), ('NGO', 'NGO')], max_length=20)),
                ('trigger_reason', models.CharField(blank=True, max_length=100)),
                ('trigger_stage', models.CharField(blank=True, max_length=30)),
                ('trigger_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('request', models.ForeignKey(db_column='request_id', on_delete=django.db.models.deletion.CASCADE, related_name='fallback_actions', to='careapp.bloodrequest')),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='RadiusExpansionLog',
            fields=[
                ('radius_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_radius_km', models.FloatField(blank=True, null=True)),
                ('new_radius_km', models.FloatField(blank=True, null=True)),
                ('expanded_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=False)),
                ('request', models.ForeignKey(db_column='request_id', on_delete=django.db.models.deletion.CASCADE, related_name='radius_expansions', to='careapp.bloodrequest')),
            ],
            options={
                'ordering': ['-expanded_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestTimeline',
            fields=[
                ('timeline_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('CREATED', 'Created'), ('SEARCH_STARTED', 'Search Started'), ('DONOR_ACCEPTED', 'Donor Accepted'), ('STANDBY_ACTIVATED', 'Standby Activated'), ('BANK_TRIGGERED', 'Bank Triggered'), ('FULFILLED', 'Fulfilled')], max_length=30)),
                ('event_time', models.DateTimeField(auto_now_add=True)),
                ('actor', models.CharField(choices=[('SYSTEM', 'System'), ('ADMIN', 'Admin'), ('DONOR', 'Donor'), ('BANK', 'Bank')], default='SYSTEM', max_length=20)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('request', models.ForeignKey(db_column='request_id', on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='careapp.bloodrequest')),
            ],
            options={
                'ordering': ['event_time'],
            },
        ),
        migrations.CreateModel(
            name='StandbyAction',
            fields=[
                ('standby_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('used', models.BooleanField(default=False)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='standby_actions', to=settings.AUTH_USER_MODEL)),
                ('donor_master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='standby_actions', to='careapp.donorprofile')),
                ('request', models.ForeignKey(db_column='request_id', on_delete=django.db.models.deletion.CASCADE, related_name='standby_actions', to='careapp.bloodrequest')),
            ],
            options={
                'ordering': ['-activated_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('area', models.CharField(blank=True, max_length=200)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('donated_before', models.BooleanField(blank=True, null=True)),
                ('last_donation_date', models.DateField(blank=True, null=True)),
                ('medical_conditions', models.BooleanField(blank=True, null=True)),
                ('currently_healthy', models.BooleanField(blank=True, null=True)),
                ('emergency_available', models.BooleanField(default=True)),
                ('preferred_contact', models.CharField(choices=[('call', 'Call'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS')], default='call', max_length=20)),
                ('consent_contact', models.BooleanField(default=False)),
                ('consent_terms', models.BooleanField(default=False)),
                ('alternate_mobile', models.CharField(blank=True, max_length=15)),
                ('preferred_language', models.CharField(blank=True, max_length=50)),
                ('preferred_contact_time', models.CharField(blank=True, max_length=50)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_number', models.CharField(blank=True, max_length=15)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='donor_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DonorResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected')], max_length=10)),
                ('responded_at', models.DateTimeField(auto_now_add=True)),
                ('blood_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='careapp.bloodrequest')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donor_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-responded_at'],
                'unique_together': {('blood_request', 'donor')},
            },
        ),
        migrations.CreateModel(
            name='HospitalMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_requests', models.PositiveIntegerField(default=0)),
                ('fulfilled', models.PositiveIntegerField(default=0)),
                ('failed', models.PositiveIntegerField(default=0)),
                ('avg_fulfillment_time', models.FloatField(blank=True, null=True)),
                ('sla_breach_pct', models.FloatField(blank=True, null=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='careapp.hospitalmaster')),
            ],
            options={
                'ordering': ['-date', 'hospital_id'],
                'unique_together': {('hospital', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blood_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='careapp.bloodrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'blood_request')},
            },
        ),
    ]
