# Generated by Django 6.0 on 2026-02-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careapp', '0002_add_request_donor_pool_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesttimeline',
            name='event_type',
            field=models.CharField(choices=[('CREATED', 'Created'), ('SEARCH_STARTED', 'Search Started'), ('DONOR_ACCEPTED', 'Donor Accepted'), ('STANDBY_ACTIVATED', 'Standby Activated'), ('STANDBY_PROMOTED', 'Standby Promoted'), ('BANK_TRIGGERED', 'Bank Triggered'), ('FULFILLED', 'Fulfilled')], max_length=30),
        ),
    ]
